a = int(input("Введите число: "))
b = int(input("Введите число: "))
c = int(input("Введите число: "))
D = (b**2-4*a*c)
print(D)
x1 = (-b+pow(D, 0.5))/(2*a)
x2 = (-b-pow(D, 0.5))/(2*a)
print(x1)
print(x2)
